// Generated by LiveScript 1.2.0
(function(){
  var requires;
  requires = require('./requires');
  module.exports = {
    AuthorizeMw: requires.mw('authorize-mw'),
    Authorizer: requires.lib('authorizer'),
    Ability: requires.lib('ability'),
    Allower: requires.lib('allower'),
    Permit: requires.lib('permit'),
    permitFor: requires.permit('permit-for')
  };
}).call(this);
