// Generated by LiveScript 1.2.0
(function(){
  var authorize, Ability, user, book, ability, aBook, currentUser;
  authorize = require('authorize-mw');
  Ability = authorize.Ability;
  user = function(name){
    return new User(name);
  };
  book = function(title){
    return new Book(title);
  };
  ability = function(user){
    return new Ability(user);
  };
  aBook = book('some book');
  currentUser = user('kris');
  if (ability(currentUser).allowedFor({
    action: 'read',
    subject: aBook
  })) {
    throw Error('unimplemented');
  }
}).call(this);
