// Generated by LiveScript 1.2.0
(function(){
  var requires, normalize, AccessRequest;
  requires = require('../requires');
  normalize = requires.lib('normalize');
  module.exports = AccessRequest = (function(){
    AccessRequest.displayName = 'AccessRequest';
    var prototype = AccessRequest.prototype, constructor = AccessRequest;
    AccessRequest.from = function(obj){
      return new AccessRequest(obj.user, obj.action, obj.subject, obj.ctx);
    };
    function AccessRequest(user, action, subject, ctx){
      this.user = user;
      this.action = action;
      this.subject = subject;
      this.ctx = ctx;
      this.normalize;
    }
    prototype.normalize = function(){
      this.action = normalize(this.action);
      return this.subject = normalize(this.subject);
    };
    return AccessRequest;
  }());
}).call(this);
