// Generated by LiveScript 1.2.0
(function(){
  var authorize, Permit, permitFor, permitClass, GuestPermit;
  authorize = require('permit-authorize');
  Permit = authorize.Permit;
  permitFor = authorize.permitFor;
  permitClass = require('../fixtures/permit-class');
  GuestPermit = permitClass.GuestPermit;
  module.exports = {
    guest: function(debug){
      return permitFor(GuestPermit, 'guest books', function(){
        return {
          rules: {
            ctx: {
              area: {
                visitor: function(){
                  return this.ucan('publish', 'Paper');
                }
              }
            },
            read: function(){
              return this.ucan('read', 'Book');
            },
            write: function(){
              return this.ucan('write', 'Book');
            },
            'default': function(){
              return this.ucan('read', 'any');
            }
          }
        };
      }, debug);
    },
    admin: function(debug){
      return permitFor(Permit, 'admin books', function(){
        return {
          rules: {
            user: {
              kris: function(){
                return this.ucan('manage', 'User');
              }
            },
            ctx: {
              area: {
                admin: function(){
                  return this.ucan('review', 'Paper');
                }
              }
            },
            subject: {
              paper: function(){
                return this.ucan('approve', 'Paper');
              }
            }
          }
        };
      }, debug);
    },
    matching: {
      user: function(){
        return permitFor('User', {
          match: function(access){
            this.debug(access);
            return this.matching(access).user();
          },
          rules: function(){
            return this.ucan(['read', 'edit'], 'book');
          }
        });
      },
      ctx: {
        auth: function(){
          return permitFor('auth', {
            match: function(access){
              return this.matching(access).hasCtx({
                auth: 'yes'
              });
            },
            rules: function(){
              return this.ucan('manage', 'book');
            }
          });
        }
      },
      role: {
        guest: function(){
          return permitFor('Guest', {
            match: function(access){
              this.debug(access);
              return this.matching(access).role('guest');
            },
            rules: function(){
              return this.ucan('read', 'book');
            }
          });
        },
        admin: function(){
          return permitFor('admin', {
            match: function(access){
              this.debug(access);
              return this.matching(access).role('admin');
            },
            rules: function(){
              this.ucan('write', 'book');
              return this.ucan('edit', 'user');
            }
          });
        }
      }
    }
  };
}).call(this);
