// Generated by LiveScript 1.2.0
(function(){
  var requires, _, lo, User, Book, createRequest, createUser, createPermit, Authorizer, Ability;
  requires = require('../../../requires');
  requires.test('test_setup');
  _ = require('prelude-ls');
  lo = require('lodash');
  User = requires.fix('user');
  Book = requires.fix('book');
  createRequest = requires.fac('create-request');
  createUser = requires.fac('create-user');
  createPermit = requires.fac('create-permit');
  Authorizer = requires.lib('authorizer');
  Ability = requires.lib('ability');
  describe('Authorizer', function(){
    var ctx, users, requests, permits, authorizers, books, book, authorizer;
    users = {};
    requests = {};
    permits = {};
    authorizers = {};
    books = {};
    book = function(title){
      return new Book({
        title: title
      });
    };
    authorizer = function(user){
      return new Authorizer(user);
    };
    before(function(){
      books.hello = book('hello');
      users.guest = createUser.guest();
      permits.guest = createPermit.matching.role.guest();
      ctx = {
        currentUser: users.guest
      };
      return authorizers.basic = authorizer(users.guest);
    });
    describe('create', function(){
      return specify('should set user', function(){
        return authorizers.basic.user.should.eql(users.guest);
      });
    });
    describe('run', function(){
      return context('read book (collection name) request by guest user', function(){
        before(function(){
          return requests.readBookCollection = {
            name: 'read',
            collection: 'books'
          };
        });
        return specify('user is authorized to perform action', function(){
          return authorizers.basic.run(requests.readBookCollectionst).should.be['true'];
        });
      });
    });
    describe('run', function(){
      return context('read actual book instance request by guest user', function(){
        before(function(){
          return requests.readBook = {
            name: 'read',
            data: book
          };
        });
        return specify('user is authorized to perform action', function(){
          return authorizers.basic.run(requests.readBook).should.be['true'];
        });
      });
    });
    return describe('run', function(){
      return context('read actual book model request by guest user', function(){
        before(function(){
          return requests.readBookModel = {
            name: 'read',
            model: book
          };
        });
        return specify('user is authorized to perform action', function(){
          return authorizers.basic.run(requests.readBookModel).should.be['true'];
        });
      });
    });
  });
}).call(this);
